import { ApiProperty } from "@nestjs/swagger";

export class Appointment {
  @ApiProperty({ example: 1, description: 'The unique ID of the appointment (optional, usually generated by the system).' })
  id?: number;

  @ApiProperty({
    example: "Oil Change",
    description: "The type of service or task required for the appointment.",
    required: true
  })
  assignment!: string;

  @ApiProperty({
    example: "Berlin",
    description: "The branch where the appointment will take place.",
    required: true
  })
  branch!: string;

  @ApiProperty({
    example: "Max Mustermann",
    description: "The name of the vehicle owner who booked the appointment.",
    required: true
  })
  vehicleOwner!: string;

  @ApiProperty({
    example: "B-AB 1234",
    description: "The license plate number of the vehicle for which the appointment is booked.",
    required: true
  })
  vehicleRegNo!: string;

  @ApiProperty({
    example: "Repair",
    description: "The current status of the appointment (e.g., scheduled, completed, canceled).",
    required: true
  })
  status!: string;

  @ApiProperty({
    example: "2024-10-01",
    description: "The date of the appointment in YYYY-MM-DD format.",
    required: true
  })
  date!: string;

  @ApiProperty({
    example: "10:30",
    description: "The time of the appointment in 24-hour format.",
    required: true
  })
  time!: string;
}
